"""
FastAPI backend for the CSE Regime-Aware Portfolio allocation model
(PPO agent over a differentiable regime encoder -- VSN+LSTM, temporal
attention, macro graph prior -- across a 10-stock CSE banking-sector
universe).

Run: uvicorn app.main:app --reload --port 8002
"""
import logging
import os
from datetime import datetime, timedelta

from cse_lib import cse_client
from cse_lib.env import load_shared_env
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

load_shared_env()  # repo-root .env -- must run before cse_bridge reads CSE_ACCESS_TOKEN

from . import config, cse_bridge, inference
from .backtest_data import get_backtest_dataset

logger = logging.getLogger("uvicorn.error")

app = FastAPI(title="CSE Regime-Aware Portfolio Allocation API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health():
    try:
        _, _, manifest = inference.load_bundle()
        checkpoint_available = True
        checkpoint_filename = manifest.get("checkpoint_filename")
    except inference.ModelNotReadyError:
        checkpoint_available = False
        checkpoint_filename = None

    return {
        "status": "ok",
        "checkpoint_available": checkpoint_available,
        "checkpoint_filename": checkpoint_filename,
        "scaler_available": os.path.exists(config.SCALER_PATH),
        "manifest_available": os.path.exists(config.MANIFEST_PATH),
        "backtest_data_available": os.path.exists(config.TEST_WEIGHTS_PATH),
        "cse_access_token_configured": bool(os.environ.get("CSE_ACCESS_TOKEN")),
    }


@app.get("/model-info")
def model_info():
    return {
        "assets": [
            {"ticker": ticker, "name": name}
            for ticker, name in config.ASSET_DISPLAY_NAMES.items()
        ],
        "initial_capital": config.INITIAL_CAPITAL,
        "disclaimer": (
            "Research prototype -- allocations are generated by a model "
            "trained on historical CSE banking-sector data (10 assets). "
            "Not investment advice."
        ),
    }


@app.get("/backtest")
def backtest():
    """Full test-set day-by-day weights + summary metrics, from the
    already-exported app/data/test_weights.csv + test_summary.json. See
    backtest_data.py for why day labels are sequential ("Day N") rather
    than real calendar dates."""
    try:
        return get_backtest_dataset()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@app.get("/cse/test")
def cse_test(symbol: str = "COMB", days: int = 30):
    """Diagnostic-only: fetch one symbol's recent history straight from CSE,
    independent of the model bundle. Use this to verify CSE_ACCESS_TOKEN and
    response shape without needing a trained checkpoint yet."""
    to_date = datetime.now()
    from_date = to_date - timedelta(days=days)
    try:
        rows = cse_bridge.fetch_symbol_history(symbol, from_date, to_date)
    except cse_client.CSEAuthError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc
    except cse_client.CSEUnavailableError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    return {"symbol": symbol, "n_rows": len(rows), "rows": rows}


@app.get("/live/today")
def live_today():
    """Live, current-day allocation: fetches the maximum real CSE daily
    history reachable in one call per asset (see cse_bridge module
    docstring for why not more), pads any shortfall against the model's
    required lookback with synthetic rows, engineers the same
    features/normalization used at training time, and runs the trained
    agent on the resulting trailing window. Needs the model bundle
    (checkpoint + scaler + manifest, shipped in app/data/models/)."""
    try:
        _, _, manifest = inference.load_bundle()
    except inference.ModelNotReadyError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    tickers = manifest["asset_names"]
    min_days = manifest.get("min_trading_days_required", 60)

    try:
        prices, volumes, n_real, n_synthetic = cse_bridge.fetch_live_matrices(tickers, min_days)
    except cse_client.CSEAuthError as exc:
        raise HTTPException(status_code=401, detail=str(exc)) from exc
    except cse_client.CSEUnavailableError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    try:
        result = inference.predict_weights(prices, volumes)
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    allocations = [
        {
            "asset": ticker,
            "name": config.ASSET_DISPLAY_NAMES.get(ticker, ticker),
            "weight": weight,
            "value_lkr": weight * config.INITIAL_CAPITAL,
        }
        for ticker, weight in result["weights"].items()
    ]
    allocations.sort(key=lambda a: a["weight"], reverse=True)

    return {
        "as_of_date": result["as_of_date"],
        "trading_days_real": n_real,
        "trading_days_synthetic": n_synthetic,
        "allocations": allocations,
        "regime_probs": result["regime_probs"],
    }
